# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1ee421cb2378d5c12d2e8db82cf62e69"
name = "Product-Customized-App"
application_url = "https://product-customized-app.onrender.com"
embedded = true

[access_scopes]
scopes = "write_products,write_metaobjects,write_metaobject_definitions,read_orders"

[product.metafields.app.demo_info]
type = "single_line_text_field"
name = "Demo Source Info"
description = "Tracks products created by the Shopify app template for development"

  [product.metafields.app.demo_info.access]
  admin = "merchant_read_write"

[metaobjects.app.example]
name = "Example"
description = "An example metaobject definition created by this template"

  [metaobjects.app.example.access]
  admin = "merchant_read_write"

[metaobjects.app.example.fields.title]
name = "Title"
type = "single_line_text_field"
required = true

[metaobjects.app.example.fields.description]
name = "Description"
type = "multi_line_text_field"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/compliance"



[auth]
redirect_urls = [
  "https://product-customized-app.onrender.com/auth/callback",
  "https://product-customized-app.onrender.com/auth/shopify/callback",
  "https://product-customized-app.onrender.com/api/auth/callback"
]

[app_proxy]
url = "https://product-customized-app.onrender.com/apps/customizer"
subpath = "customizer"
prefix = "apps"

[build]
automatically_update_urls_on_dev = false
